### ISSUE TITLE
Start Day & Discussion End Event Handler

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#109]
### In-Depth Feature Description:
Implement the event handlers for events (`start-day` and `discussion-end`) during the "day time" phase of a game. During the discussion phase, players will be discussing who they think is guilty. At the end of their allocated discussion time, they must put in votes for who they think is guilty. The player(s) with the highest votes will be put on trial.

### Images for Reference:

N/A

### Blocked by issues:

None

### Sub-Task List:

- [x] Listener/handler for "start-day" event
- [x] Listener/handler for "discussion-end" event

### Issue Approval:

- [ ] Issue approved by:
