### ISSUE TITLE
Start Trial & Trial End Event Handler

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#110]
### In-Depth Feature Description:
Implement the event handlers for events during the "trial time" phase of a game (`start-trial` and `trial-end`). During the trial time, players on trial will get the chance to defend themselves. During the trial, people can send votes for who they want to chop off the group, or choose to not put anyone on the chopping block at all.

### Images for Reference:

N/A

### Blocked by issues:

None

### Sub-Task List:

- [x] Listener/handler for "start-trial" event
- [x] Listener/handler for "trial-end" event

### Issue Approval:

- [ ] Issue approved by:
