### ISSUE TITLE
Add Intellisense for JEST

### ISSUE THREAD

**Issue by parfei** [Mafia-Hands/Mafia#137]
### In-Depth Feature Description:
We would like intellisense for Jest. This would make writing tests much easier, as we are less likely to muck up function call names and we can also discover other functions that we can use for mocking/spying/testing our implementation efficiently.

### Images for Reference:
![image](https://user-images.githubusercontent.com/42878423/111381212-43b09200-870a-11eb-8723-bdb986369ad2.png)

### Sub-Task List:

- [x] Install types for Jest
- [x] Add a jsconfig.json file that defines the project context, so that we can use the types in our tests.

### Issue Approval: 

- [x] Issue approved by: @LindaBot
