### ISSUE TITLE
Integration Tests for NightStateChange and GameStartEvents

### ISSUE THREAD

**Issue by UltimaKuma** [Mafia-Hands/Mafia#142]
### In-Depth Feature Description:
Creating integration tests for NightStateChnage and GameStartEvents

### Sub-Task List:

- [x] Tests for NightStateChange 
- [x] Tests for GameStartEvents

### Issue Approval:

- [x] Issue approved by: @reeved
