### ISSUE TITLE
Integration Tests for LobbyEvents, VoteEvents and NightTimeVoteEvent

### ISSUE THREAD

**Issue by UltimaKuma** [Mafia-Hands/Mafia#143]
### In-Depth Feature Description:
Creating integration tests for LobbyEvents, VoteEvents and NightTimeVoteEvent

### Sub-Task List:

- [x] Tests for LobbyEvents
- [x] Tests for NightTimeVoteEvent
- [x] Tests for VoteEvents

### Issue Approval:

- [x] Issue approved by: @reeved
