### ISSUE TITLE
game-over Event Handler

### ISSUE THREAD

**Issue by MKTPR** [Mafia-Hands/Mafia#157]
**Is your feature request related to a problem? Please describe.**
An event which is sent to the client to end the game when a winning condition has been achieved. 

**Describe the solution you'd like**
The game over event will include a player role and the list of player nicknames who has won. 

### Sub-Task List:

- [ ] Listener/handler for "game-over" event
- [ ] Logic implementation to check win condition
- [ ] Logic implementation to return winning players

### Feature Approval:
- [x]  Feature approved by: @parfei
