### ISSUE TITLE
Restructure backend unit testing

### ISSUE THREAD

**Issue by seif-y** [Mafia-Hands/Mafia#164]
### In-Depth Feature Description:

The backend unit tests are quire monolithic at the moment, so they need to be restructured to make it easier to add more tests. This involves:
- Creating more files/test suites to separate different test cases
- Set up more robust mock objects that can be used to test late-game functionalities

### Images for Reference:

N/A
### Blocked by issues:
N/A

### Sub-Task List:

- [ ] Mock objects for game starts and adding players.
- [ ] Separation of tests to different suites, where similar test cases are grouped together.
- [ ] Adding unit tests for voting events.

### Issue Approval:

- [x] Issue approved by: @MKTPR
