### ISSUE TITLE
Integration Tests for DayStateChange and TrialStateChange

### ISSUE THREAD

**Issue by UltimaKuma** [Mafia-Hands/Mafia#194]
### In-Depth Feature Description:
Creating integration tests for DayStateChange and TrialStateChange

### Sub-Task List:

- [x] Tests for DayStateChange
- [x] Tests for TrialStateChange

### Issue Approval:

- [ ] Issue approved by:
