### ISSUE TITLE
Prevent Jesters from winning by Mafia Kill

### ISSUE THREAD

**Issue by reeved** [Mafia-Hands/Mafia#201]
### In-Depth Feature Description:
At the moment, Jesters win even when they get killed by Mafia in the night. They should only win if they get voted out by Trial.
A suggested fix is to have a flag like `jesterMafiaKill` that is also considered when checking the Jester win condition. This flag would be set when a Mafia kills the jester. That way, it will always be true after that and Jesters will never pass the win condition check. 

### Images for Reference:
**CURRENT:**
![image](https://user-images.githubusercontent.com/7234148/111856708-77e9b400-8991-11eb-9590-18839835695d.png)
**SUGGESTED:**
![image](https://user-images.githubusercontent.com/7234148/111856716-859f3980-8991-11eb-911d-d457e1d8d2ea.png)

### Blocked by issues:
None

### Sub-Task List:
- [ ] Add a flag to check if the Jester was killed by Mafia
- [ ] Check flag when checking Jester win Condition.

### Issue Approval:

- [x] Issue approved by: Seif

**Comment by seif-y** [comment]
Another way to do this would be to replace the `isAlive` boolean with something like `playerStatus`, which could be an enum with the values `ALIVE`, `KILLED_BY_MAFIA` and `KILLED_BY_TOWN`, which would let us distinguish between different causes of death for a player. The method you described is fine with me though, just want to present an alternative idea.
