### ISSUE TITLE
Extend the game to support up to 7 Players

### ISSUE THREAD

**Issue by ODE-BOY** [Mafia-Hands/Mafia#283]
### Is your feature request related to a problem? Please describe.
I am only able to play the game with 6 friends. 

### Describe the solution you'd like
The option for up to 7 players to join a single lobby

### Linked with issues:
- [ ] #262 
- [ ] #284 

### Sub-Task List:

- [ ] Understand the Existing Front and Backend Lobby Size Code
- [ ] Understand how the currently hardcoded '6' players affect the program.

**Additional context**
A lot of the existing logic for the view, players joining, role allocation and win condition checks has been implemented in a way that allows for easily extending the game to support more players. 

### Feature Approval:
- [x]  Feature approved by: @RawiriHohepa
