### ISSUE TITLE
Testing of the 7 Person Lobby Expansion

### ISSUE THREAD

**Issue by ODE-BOY** [Mafia-Hands/Mafia#284]
### In-Depth Feature Description:
Add Tests for a seven-person game.

### Linked with issues:
- [x] #283 

### Sub-Task List:

- [x] Understand the Existing Tests
- [x] Understand how the currently hardcoded '6' players affect the program.

### Issue Approval:

- [x] Issue approved by: Rawiri
