### ISSUE TITLE
Design the application domain model

### ISSUE THREAD

**Issue by SreenikethRaghavan** [Mafia-Hands/Mafia#49]
### Description
Need to design domain model objects which will be used to encapsulate the key details of entities in the Mafia gaming environment. These include:
- The Lobby which represents a session which multiple players can join
    - Properties: `roomName (lobby code), players[], gameState, roundNumber`
- The players joining the game, their details and identifying information
    - Properties: `socketID, nickname, role, isAlive`
- The roles held by the players (mafia, detective, etc.)
    - Enum values: `Mafia, Detective, Medic, Civilian` 
- The different game states which represent the different phases in the game cycle
    - Game states: `Night Time, Day Time, Initial Vote, Trial`
- A container to represent all the ongoing game sessions which is a collection of all the active lobbies
    - Property: `Map(roomID, Room)`

### Sub-Task List
- [x] Create a base domain model for Lobby, Player, Role, Game State and Lobby Container with properties
- [x] Add getter and setter functions
- [x] Add tests to the CI pipeline to test the functionality 

### Issue Approval
- [x]  Issue approved by: Dhors (Daniel Hor), Jteo97 (Justin Teo)
