### ISSUE TITLE
ESLint Testing with Prettier

### ISSUE THREAD

**Issue by MKTPR** [Mafia-Hands/Mafia#57]
**Is your feature request related to a problem? Please describe.**
Set up a config and an eslint file for the project to keep consistent linting rules for all participating developers.
This would prevent the developer from committing or pushing any code that doesn't follow the correct linting format. 

**Describe the solution you'd like**
Create a prettier config in the root directory to be shared by frontend and backend.

### Feature Approval:
- [x]  Feature approved by: @LindaBot 

### Sub-Task List:
- [ ] Prettier Config file
- [ ] .eslintrc.json file
- [ ] Update package.json for new dependencies on eslint and prettier
        - Backend can refer to the this PR #47 for the new packages / scripts required
- [ ] Add new line at the end of the file
- [ ] Increase the file width tolerance

- [x] Issue approved by: @parfei
