### ISSUE TITLE
Develop the voting event handlers

### ISSUE THREAD

**Issue by jteo97** [Mafia-Hands/Mafia#78]
### In-Depth Feature Description:
Both the day vote and trail vote event handlers need to be developed along with associated game logic such as:
- storing votes for each player in their room object
- tallying votes for each player
- responding with votes to all players at the end 

This is a core feature for the Mafia game to function.

### Sub-Task List:

- [x] Create a skeleton for both event handlers
- [x] Add the logic to actually alter game state when these handlers are called
- [x] Add tests for each event handler to test functionality

### Issue Approval:

- [x] Issue approved by: all members of the backend team
