### ISSUE TITLE
Night Time Voting Implementation

### ISSUE THREAD

**Issue by seif-y** [Mafia-Hands/Mafia#79]
### In-Depth Feature Description:
Implement the event handlers for voting events during the "night time" phase of a game. This involves taking votes from players, and tallying them up.

### Images for Reference:

N/A

### Blocked by issues:

None

### Sub-Task List:

- [ ] Listener/handler for "mafia-vote" event
- [ ] Listener/handler for "detective-vote" event, including sending of "suspect-reveal" afterwards.
- [ ] Listener/handler for "medic-vote" event

### Issue Approval:

- [x] Issue approved by: Jennifer
