### ISSUE TITLE
Create create-lobby and lobby-code event handlers

### ISSUE THREAD

**Issue by LindaBot** [Mafia-Hands/Mafia#81]
### In-Depth Feature Description:
At the start of mafia, a host will need to be able to create a game and share the code with their 5 other friends to join the game. 

This issue replaces #48 as the scope for that issue was too big.

### Sub-Task List:

- [ ] Create `create-lobby` handlers for an event rasied by the client
- [ ] Create `lobby-code` to emit to the clients connected to inform the newly generated lobby-code (roomID)
- [ ] Create associated unit tests

### Issue Approval:

- [x] Issue approved by the team during the backend team discussion
