### ISSUE TITLE
Reset Lobby Implementation

### ISSUE THREAD

**Issue by UltimaKuma** [Mafia-Hands/Mafia#83]
### In-Depth Feature Description:
Create endpoint "reset-lobby" to reset the lobby, should also send the respective "reset-lobby-update" to all players in lobby to update client state. Would involve resetting all information related to the previous game.

### Images for Reference:
N/A

### Blocked by issues:
None

### Sub-Task List:
- [x] Listener/handler for "reset-lobby" event
- [x] Emission of "reset-lobby-update" response
- [x] Tests for "reset-lobby"
- [x] Headers and comments for "reset-lobby"
- [ ] Please set socket.player = null

### Issue Approval:

- [x] Issue approved by: Jennifer
