### ISSUE TITLE
Develop join lobby event handler

### ISSUE THREAD

**Issue by jteo97** [Mafia-Hands/Mafia#84]
### In-Depth Feature Description:
This feature is to let players join the lobby. It requires setting up the server and client connection along with assigning the joining player to the correct room using a room code.

This is a core feature for the Mafia game to function.

### Sub-Task List:
- [x] Create the event handler which handles joining of lobbies 
- [x] Create tests that test the event handler created

### Issue Approval:

- [x] Issue approved by: all members of the backend team
