### ISSUE TITLE
Create game ready event handler.

### ISSUE THREAD

**Issue by Dhors** [Mafia-Hands/Mafia#87]
### In-Depth Feature Description:
This feature is to let players know the lobby is full and ready to start. It requires the host to be allowed to start the game and informing the non-host players that the game will be starting. This involves sending two different events to the host and non-host players respectively.

This is the last stage of screens before the game begins.

### Sub-Task List:
- [x] Create event handler for the lobby filling up. 
- [x] Create tests to test functionality of event handler.

### Issue Approval:

- [x] Issue approved by: @LindaBot
